map_server:
  ros__parameters:
    use_sim_time: True
    # yaml_filename은 런치 파일에서 넘겨주지만, 
    # 선언이 되어있지 않으면 에러가 나는 경우가 있습니다.
    yaml_filename: "/home/dtv/ros2_ws/src/my_map/maps/my_world_map.yaml" 
amcl:
  ros__parameters:
    use_sim_time: true
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    base_frame_id: "base_link"
    min_particles: 500
    max_particles: 2000
    odom_frame_id: "odom"
    scan_topic: "scan"
    

bt_navigator:
  ros__parameters:
    use_sim_time: True
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odom
    bt_loop_duration: 10
    default_server_timeout: 20

controller_server:
  ros__parameters:
    use_sim_time: True
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["general_goal_checker"]
    controller_plugins: ["FollowPath"]
    
    # 필수 플러그인 설정
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0
    general_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: True
      min_vel_x: 0.0
      min_vel_y: 0.0
      max_vel_x: 0.26
      max_vel_y: 0.0
      max_vel_theta: 1.0
      min_speed_xy: 0.0
      max_speed_xy: 0.26
      min_speed_theta: 0.0
      # 에러의 원인: 아래 Critics 설정이 반드시 포함되어야 합니다.
      critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
      RotateToGoal:
        plugin: "dwb_critics::RotateToGoalCritic"
      Oscillation:
        plugin: "dwb_critics::OscillationCritic"
      BaseObstacle:
        plugin: "dwb_critics::BaseObstacleCritic"
      GoalAlign:
        plugin: "dwb_critics::GoalAlignCritic"
      PathAlign:
        plugin: "dwb_critics::PathAlignCritic"
      PathDist:
        plugin: "dwb_critics::PathDistCritic"
      GoalDist:
        plugin: "dwb_critics::GoalDistCritic"
    
planner_server:
  ros__parameters:
    use_sim_time: True
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.05
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"

lifecycle_manager_localization:
  ros__parameters:
    use_sim_time: True
    autostart: True
    node_names: ['map_server', 'amcl']