# Nav2 Parameters Configuration
# 경로: /home/dtv/ros2_ws/src/my_map/params/nav2_params.yaml

amcl:
  ros__parameters:
    use_sim_time: true
    
    # Frame 설정
    global_frame_id: "map"
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    
    # TF 발행
    tf_broadcast: true
    transform_tolerance: 0.5
    
    # 초기 위치 설정
    set_initial_pose: true
    initial_pose:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0
    
    # 모션 모델
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    
    # 모션 노이즈 파라미터 (낮을수록 정확)
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.3
    alpha4: 0.3
    alpha5: 0.2
    
    # 파티클 필터
    min_particles: 500
    max_particles: 3000
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_slow: 0.0
    recovery_alpha_fast: 0.0
    resample_interval: 1
    
    # 레이저 스캔 설정
    scan_topic: "scan"
    laser_model_type: "likelihood_field"
    laser_likelihood_max_dist: 4.0
    laser_max_range: 12.0
    laser_min_range: 0.15
    max_beams: 120
    
    # 업데이트 임계값 (낮을수록 자주 업데이트)
    update_min_d: 0.05
    update_min_a: 0.05
    resample_interval: 1   # 매번 샘플링 수행
    # 위치 저장
    save_pose_rate: 0.05
    always_reset_initial_pose: false

bt_navigator:
  ros__parameters:
    use_sim_time: true
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odom
    # [수정 1] 빈 문자열 "" 대신 실제 경로를 넣어야 합니다. ""는 정말 '빈 트리'를 의미합니다.
    default_bt_xml_filename: "/opt/ros/humble/share/nav2_bt_navigator/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml"
    default_nav_to_pose_bt_xml: "/opt/ros/humble/share/nav2_bt_navigator/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml"
    default_nav_through_poses_bt_xml: "/opt/ros/humble/share/nav2_bt_navigator/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml"
    bt_loop_duration: 10
    default_server_timeout: 20
    navigators: ['navigate_to_pose', 'navigate_through_poses']
    navigate_to_pose:
      plugin: "nav2_bt_navigator/NavigateToPoseNavigator"
    navigate_through_poses:
      plugin: "nav2_bt_navigator/NavigateThroughPosesNavigator"

    # [수정 2] plugin_lib_names가 두 번 적혀있던 것을 하나로 합쳤습니다.
    plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_compute_path_through_poses_action_bt_node
      - nav2_smooth_path_action_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_spin_action_bt_node
      - nav2_wait_action_bt_node
      - nav2_back_up_action_bt_node
      - nav2_drive_on_heading_bt_node
      - nav2_clear_costmap_service_bt_node
      - nav2_is_stuck_condition_bt_node
      - nav2_goal_reached_condition_bt_node
      - nav2_goal_updated_condition_bt_node
      - nav2_initial_pose_received_condition_bt_node
      - nav2_rate_controller_bt_node
      - nav2_distance_controller_bt_node
      - nav2_speed_controller_bt_node
      - nav2_truncate_path_action_bt_node
      - nav2_goal_updater_node_bt_node
      - nav2_recovery_node_bt_node
      - nav2_pipeline_sequence_bt_node
      - nav2_round_robin_node_bt_node
      - nav2_transform_available_condition_bt_node
      - nav2_time_expired_condition_bt_node
      - nav2_distance_traveled_condition_bt_node
      - nav2_single_trigger_bt_node
      - nav2_navigate_through_poses_action_bt_node
      - nav2_navigate_to_pose_action_bt_node
      - nav2_planner_selector_bt_node
      - nav2_controller_selector_bt_node
      - nav2_goal_checker_selector_bt_node

controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.01
    failure_tolerance: 0.3
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["general_goal_checker"]
    controller_plugins: ["FollowPath"]
    
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.2
      movement_time_allowance: 10.0
      
    general_goal_checker:
      stateful: true
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.05
      yaw_goal_tolerance: 0.1
      
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: true
      TrajectoryStaticsCritic.scale: 1.0
      # 1. 촘촘한 충돌 검사 (순간이동/벽뚫기 방지 핵심)

      # 2. 회전 및 주행 속도 제한 (ㄷ자 코너 주행 안정화)
      acc_lim_x: 1.0         # 급출발 방지

      # 3. 가중치 설정 (장애물 방어 vs 경로 추종 밸런스)
      BaseObstacleCritic.scale: 15.0  # 벽에 대한 공포심 (가장 중요)
      PathAlignCritic.scale: 20.0     # 글로벌 경로를 따라가는 힘
      PathDistCritic.scale: 20.0      # 경로와의 거리 유지
      GoalAlignCritic.scale: 5.0      # 목적지로만 달려드는 성향 억제
      
      # 회전 시 내륜차/스윙 반경 보정 (항아리형 footprint 효과)
      scaling_speed: 0.2
      max_scaling_factor: 0.2
      
      # 속도 제한
      min_vel_x: 0.0
      min_vel_y: 0.0
      max_vel_x: 0.1
      max_vel_y: 0.0
      max_vel_theta: 0.5
      min_speed_xy: 0.05
      max_speed_xy: 0.2
      min_speed_theta: 0.0
      
      # 가속도 제한
      acc_lim_x: 0.5
      acc_lim_y: 0.0
      acc_lim_theta: 1.0
      decel_lim_x: -1.0
      decel_lim_y: 0.0
      decel_lim_theta: -1.5
      
      # 궤적 생성
      vx_samples: 40
      vy_samples: 0
      vtheta_samples: 40
      sim_time: 1.7
      sim_granularity: 0.02
      discretize_by_time: false
      linear_granularity: 0.01
      angular_granularity: 0.015
      
      # Critics 설정
      critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
      # BaseObstacle.scale: 15.0
      PathAlign.scale: 15.0
      PathDist.scale: 15.0
      PathAlign.forward_point_distance: 0.1
      GoalAlign.scale: 5.0
      GoalAlign.forward_point_distance: 0.1
      GoalDist.scale: 5.0
      RotateToGoal.scale: 10.0
      RotateToGoal.slowing_factor: 5.0
      RotateToGoal.lookahead_time: -1.0
      Oscillation.scale: 1.0
      Oscillation.x_only_threshold: 0.05

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: true
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.01
      # robot_radius: 0.1  <-- 이 줄을 주석 처리하거나 삭제하세요.
      footprint: "[ [0.10, 0.06], [0.10, -0.06], [0.0, -0.07], [-0.10, -0.06], [-0.10, 0.06], [0.0, 0.07] ]"
      plugins: ["voxel_layer", "inflation_layer"]
      
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 10.0
        inflation_radius: 0.13
        
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: true
        publish_voxel_map: true
        origin_z: 0.0
        z_resolution: 0.01
        z_voxels: 16
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: true
          marking: true
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 1.5
          obstacle_min_range: 0.0
      
      always_send_full_costmap: true

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: true
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      footprint: "[ [0.10, 0.06], [0.10, -0.06], [0.0, -0.07], [-0.10, -0.06], [-0.10, 0.06], [0.0, 0.07] ]"
      resolution: 0.01
      track_unknown_space: true
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: true
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: true
          marking: true
          data_type: "LaserScan"
          raytrace_max_range: 2.0
          raytrace_min_range: 0.0
          obstacle_max_range: 1.5
          obstacle_min_range: 0.0
          
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: true
        subscribe_to_updates: true
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 5.0
        inflation_radius: 0.2
        
      always_send_full_costmap: true

map_server:
  ros__parameters:
    use_sim_time: true
    yaml_filename: "/home/dtv/ros2_ws/src/my_map/maps/my_world_map.yaml"

planner_server:
  ros__parameters:
    use_sim_time: true
    expected_planner_frequency: 20.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 2.0
      use_astar: true
      allow_unknown: true

smoother_server:
  ros__parameters:
    use_sim_time: true
    smoother_plugins: ["simple_smoother"]
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-10
      max_its: 1000
      do_refinement: true

behavior_server:
  ros__parameters:
    use_sim_time: true
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["spin", "backup", "drive_on_heading", "wait"]
    spin:
      plugin: "nav2_behaviors/Spin"
    backup:
      plugin: "nav2_behaviors/BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading"
    wait:
      plugin: "nav2_behaviors/Wait"
    global_frame: odom
    robot_base_frame: base_link
    transform_tolerance: 0.1
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2

robot_state_publisher:
  ros__parameters:
    use_sim_time: true

waypoint_follower:
  ros__parameters:
    use_sim_time: true
    loop_rate: 20
    stop_on_failure: false
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: true
      waypoint_pause_duration: 200

velocity_smoother:
  ros__parameters:
    use_sim_time: true
    smoothing_frequency: 20.0
    scale_velocities: false
    feedback: "OPEN_LOOP"
    max_velocity: [0.5, 0.0, 1.5]
    min_velocity: [0.0, 0.0, -1.5]
    max_accel: [0.5, 0.0, 1.0 ]
    max_decel: [-2.5, 0.0, -3.2]
    odom_topic: "odom"
    odom_duration: 0.1
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 1.0

collision_monitor:
  ros__parameters:
    use_sim_time: true
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    cmd_vel_in_topic: "cmd_vel_smoothed"
    cmd_vel_out_topic: "cmd_vel"
    state_topic: "collision_monitor_state"
    transform_tolerance: 0.2
    source_timeout: 1.0
    base_shift_correction: true
    stop_pub_timeout: 2.0
    polygons: ["FootprintApproach"]
    FootprintApproach:
      type: "polygon"
      action_type: "approach"
      footprint_topic: "local_costmap/published_footprint"
      time_before_collision: 1.2
      simulation_time_step: 0.1
      min_points: 6
      visualize: false
      enabled: true
    observation_sources: ["scan"]
    scan:
      type: "scan"
      topic: "scan"
      min_height: 0.05
      max_height: 0.5
      enabled: true

lifecycle_manager_localization:
  ros__parameters:
    use_sim_time: true
    autostart: true
    node_names: ['map_server', 'amcl']

lifecycle_manager_navigation:
  ros__parameters:
    use_sim_time: true
    autostart: true
    node_names: [
      'controller_server',
      'planner_server',
      'behavior_server',
      'bt_navigator',
      'waypoint_follower',
      'velocity_smoother'
    ]